#simple IOS config in ansible
---
- name: Sample IOS config for Ansible 2.5+
  hosts:
    - ios-xe-mgmt.cisco.com
  gather_facts: no
  vars_prompt:
    - name: loopback_num
      prompt: "What Loopback Number to Configure?"
      private: no
    - name: loopback_ip
      prompt: "What IP address to use? Example 192.168.1.1/32"
      private: no

  tasks:

  - name: Create loopback {{loopback_num}}
    ios_interface:
      name: Loopback{{loopback_num}}
      enabled: True
      description: Created with Ansible
  - name: Assign IP to loopback
    ios_l3_interface:
      name: Loopback{{loopback_num}}
      ipv4: "{{loopback_ip}}"
  - name: Gather listed interfaces with provided configurations
    cisco.ios.ios_interfaces:
      config:
      state: gathered
    register: interface_info
  - name: Print the output
    debug: var=interface_info

#Open a change validation Ticket back to ServiceNow with details

- name: Create ticket with notes
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  - name: Create a change request
    snow_record:
      state: present
      table: change_request
      username: "{{ sn_username }}"
      password: "{{ sn_password }}"
      instance: "{{ sn_instance }}"
      data:
        severity: "{{ sn_severity }}"
        priority: "{{ sn_priority }}"
        short_description: "This is a test opened by Ansible"
        work_notes : "{{ interface_info }}"
    register: new_incident

  - debug: 
      var: new_incident.record
